### ISSUE TITLE
Missing RuboCop::Cop::PackwerkLite::Base when rails environment is loaded

### ISSUE THREAD

**Issue by ransombriggs** [rubyatscale/rubocop-packs#47]
After installing `pack_stats` and `rubocop-packs` I am getting a `NameError` when it is loaded in my rails environment.  I went looking through the codebase for the `Base` class to see if I could fix it with a PR, but could not find one anywhere, am I missing something?

```
# I trimmed out extraneous bits from the paths
rake aborted!
NameError: uninitialized constant RuboCop::Cop::PackwerkLite::Base
Did you mean?  Base64
gems/rubocop-packs-0.0.30/lib/rubocop/cop/packwerk_lite/privacy_checker.rb:40:in `<module:PackwerkLite>'
gems/rubocop-packs-0.0.30/lib/rubocop/cop/packwerk_lite/privacy_checker.rb:5:in `<module:Cop>'
gems/rubocop-packs-0.0.30/lib/rubocop/cop/packwerk_lite/privacy_checker.rb:4:in `<module:RuboCop>'
gems/rubocop-packs-0.0.30/lib/rubocop/cop/packwerk_lite/privacy_checker.rb:3:in `<main>'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/rubocop-packs-0.0.30/lib/rubocop/packwerk_lite.rb:6:in `<main>'
gems/rubocop-packs-0.0.30/lib/rubocop-packs.rb:9:in `require_relative'
gems/rubocop-packs-0.0.30/lib/rubocop-packs.rb:9:in `<main>'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/pack_stats-0.0.1/lib/pack_stats/private/metrics/packwerk_checker_usage.rb:4:in `<main>'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/pack_stats-0.0.1/lib/pack_stats/private/datadog_reporter.rb:8:in `<main>'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/pack_stats-0.0.1/lib/pack_stats.rb:12:in `<main>'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
gems/bundler-2.3.22/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `each'
gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `block in require'
gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `each'
gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `require'
gems/bundler-2.3.22/lib/bundler.rb:187:in `require'
rails/config/application.rb:19:in `<top (required)>'
rails/Rakefile:1:in `require'
```

**Comment by ransombriggs** [comment]
A co-worker pointed out that it is probably trying to extend `RuboCop::Cop::Base` and I threw a debugger in when running specs and verified that is why specs are passing for me and failing in my environment.

```
=> 41:       class Privacy < Base
   42:         extend T::Sig
   43: 
   44:         sig { returns(T::Boolean) }
   45:         def support_autocorrect?
(byebug) Base
RuboCop::Cop::Base
```

**Comment by ransombriggs** [comment]
And that is because we are an ancient version of rubocop (0.81.0) and it was not added till [0.87.0](https://github.com/rubocop/rubocop/commit/f8813e76cef5c06cfe1f3a73b032f4f06de7de6c), will try upgrading.

**Comment by alexevanczuk** [comment]
Thanks for the issue reporting @ransombriggs ! Let me know if upgrading doesn't resolve your issue!

**Comment by ransombriggs** [comment]
Upgrading to 0.90.0 worked for me (needed to go past 0.87.0 to get an unrelated fix)
